//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMPReview.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public Nullable<int> Rating { get; set; }
        public int BusinessId { get; set; }
        public string Text { get; set; }
        public string UserId { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual User User { get; set; }
    }
}
