// <auto-generated />
namespace WMPReview.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class removefieldsfrombusiness : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removefieldsfrombusiness));
        
        string IMigrationMetadata.Id
        {
            get { return "201501170240574_removefieldsfrombusiness"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
